FROM openjdk
MAINTAINER Hakim Arhazzal <hakim.arhazzal@gmail.com>
ADD target/service-config-0.0.1-SNAPSHOT.jar service-config-0.0.1-SNAPSHOT.jar.jar
ENTRYPOINT ["java", "-jar", "/service-config-0.0.1-SNAPSHOT.jar"]
EXPOSE 3333